### ISSUE TITLE
Issue since instaling Home Assistant core 2024.2

### ISSUE THREAD

**Issue by jmbinette** [djtimca/haomnilogic#58] opened 2024-02-08 19:40 UTC
After 2024.2 installation, I get this error.

2024.2 uses Python version 3.12

Setup failed for custom integration 'omnilogic': Unable to import component: No module named 'importlib_metadata'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/omnilogic/__init__.py", line 12, in <module>
    from .common import OmniLogicUpdateCoordinator
  File "/config/custom_components/omnilogic/common.py", line 6, in <module>
    from importlib_metadata import NullFinder
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by djtimca** [comment] 2024-02-08 19:41
Duplicate of #57 - already fixed in latest release.

**Closed by djtimca** 2024-02-08 19:41 UTC
Labels: duplicate

**Comment by jmbinette** [comment] 2024-02-08 19:42
My bad, did not look at closed issue since it was so new !

Thanks!
