### ISSUE TITLE
Can't see my valves in HA 

### ISSUE THREAD

**Issue by knwpsk** [djtimca/haomnilogic#37] opened 2022-10-11 20:23 UTC
Just installed this integration.
I see all of the devices/entities that I expect, but not the two motorized valves in my system. Without the valves, I can't create the automations I want (switch from Pool Mode to Spa Mode, etc).

From various other notes and tickets, it appears that "some" users can see and control their valves. How do I troubleshoot this? 

Thanks

**Comment by knwpsk** [comment] 2022-10-12 14:40
Experimented some last night and this might be helpful:

The devices/entities that I see are just the ones that the integration automatically found when I installed it.
They include:
- Filter Pump
- Spa Pump
- Cleaner Pump

But I don't actually have a "spa pump", I just have two pumps (Filter/main, and Cleaner/booster). The Filter/Main pump pushes water out to one of those motorized valves, which chooses between the pool and the spa. 

With my system currently in Pool mode, I tried "turning on" the "spa pump" in HA. The following things happened:
- The pump stopped
- The valve switched from Pool to Spa
- The pump restarted
- (The heater did NOT come on)
- (The lights did NOT come on)

So, what HA perceives as "Spa Pump" device, isn't actually a device, it's a "Mode" (my word) in the Omnilogic controller. But it's also not a "Theme" -- because the themes I have saved also turn on the heater and the lights.

**Comment by twillux** [comment] 2023-02-07 19:51
@knwpsk Wanted to share that your testing is spot-on regarding how the Omnilogic controller works. The Omnilogic does not expose individual valves; instead, valves are assigned to equipment. When equipment control is performed, the valves will toggle their state. I had some confusion as well when first setting up my controller when the pool was completed, as this wasn't exactly intuitive. 

In your case, just like mine, your controller is setup in Shared Equipment mode, where the pool and spa both share the same pump and filter. The Omnilogic then represents this as a Pool Pump and a Spa Pump, even though they're one and the same. To change mode, you simply take an action on either pump (turn on, change speed, etc.), and the controller then flips the valves to change the mode. As another example, I have a pool chiller with an inlet valve tied to it; when I turn on the chiller, the valve opens automatically. When I turn it off, the valve closes.

In the HA integration, it works exactly the same way. You can tell which "mode" you're in by checking if the Pool or Spa pump is on, or which temperature is actually showing a realtime value and not "unknown". You could also create a template sensor in HA if you wanted to be able to track the actual "mode" status between pool and spa.

In the end, the integration is working as intended, and matches how both the Omnilogic controller, web portal, and phone applications work.

**Comment by knwpsk** [comment] 2023-02-07 20:45
@twillux thanks! Great explanation.
I'm ok with closing this ticket.
(Maybe it would be useful to add some of this to the HA integration page? https://www.home-assistant.io/integrations/omnilogic/)

**Closed** 2024-01-22 20:08 UTC
